services:
  - type: web
    name: email-bot
    env: docker
    plan: free
    healthCheckPath: /health
    startCommand: sleep 30 && gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 900
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    healthCheck:
      grace_period: 900s
      interval: 20s
      timeout: 900s
      method: get
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
