services:
  - type: web
    name: email-bot
    env: docker
    plan: free
    healthCheckPath: /health
    healthCheckTimeout: 900 # 15 minutes in seconds
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
