services:
  - type: web
    name: email-bot
    env: docker
    plan: free
    buildCommand: docker build -t email-bot .
    startCommand: gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 900 --keep-alive 120
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: OPENAI_API_KEY
        sync: false
